<!-- date-mage-init -->
<div data-mage-init='{"functionSetId": {}}' id='div1' class='div1'>+</div> <!-- function -->
<div data-mage-init='{"objectSetId": {}}' id='div2' class='div2'>+</div> <!-- object -->
<div data-mage-init='{"widgetSetId": {}}' id='div3' class='div3'>+</div> <!-- widget -->

<!-- text/javascript -->
<div id='div4' class='div4'>+</div> <!-- function -->
<div id='div5' class='div5'>+</div> <!-- object -->
<div id='div6' class='div6'>+</div> <!-- widget -->

<!-- text/x-magento-init with selector -->
<div id='div7' class='div7'>+</div> <!-- function -->
<div id='div8' class='div8'>+</div> <!-- object -->
<div id='div9' class='div9'>+</div> <!-- widget -->

<!-- text/x-magento-init without selector -->
<div id='div10' class='div10'>+</div> <!-- function -->
<div id='div11' class='div11'>+</div> <!-- object -->
<div id='div12' class='div12'>+</div> <!-- widget -->

<script type='text/javascript'>

    require([
            'jquery',
            'functionSetId',
            'objectSetId',
            'widgetSetId',
            'underscoreTutorial'
        ], function($, functionSetId, objectSetId, widgetSetId, underscoreTutorial) {

        functionSetId({'id':'div4'})

        objectSetId.objectSetId({'id':'div5'})

        widgetSetId({'id':'div6'});

        underscoreTutorial();


    });
</script>


<script type='text/x-magento-init'>
        {
            "#div7": {
                "functionSetId": {}
            },

            "#div8": {
                "objectSetId": {}
            },

            "#div9": {
                "widgetSetId": {}
            },

            "*": {
                "functionSetId": {"id": "div10"},
                "objectSetId": {"id": "div11"},
                "widgetSetId": { "id": "div12"}
            }
        }
</script>

