<div data-mage-init='{"prototypeExample": {}}' id='div1'>+</div> <!-- function -->

<table border="1">
    <tbody>
    <tr>
        <td id="td1">"first col"</td>
        <td id="td2">"sec col"</td>
        <td id="td3">"third col"</td>
    </tr>
    </tbody>
</table>

<button type="button" class="action" data-trigger="trigger">
    <span data-bind="i18n: 'Click Here'"></span>
</button>
<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Popup title',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('Submit'),
                class: 'action'
            }]
        }}">
    <div class="content">
        Popup Content
    </div>
</div>
