<?php
use Learning\PageLayout\Block\TestBlock;
/** @var TestBlock $block */
use Magento\Framework\Escaper;

/** @var Escaper $escaper */



// Output in single quotes does not need escaping (for example echo ‘some text’)
echo '<strong> apple </strong><br>';

// Output in double quotes without variables does not need escaping (for example echo “some text”)

/* Example 1 - escapeHtml */
$block->setTitle("<script>alert('hello');</script>");

/* Example 2 - escapeJs */
$egypt = 'การรักษาความปลอดภัยแม่แบบ';

/* Example 3 - escapeHtmlAttr */
$data = [
];

$dataJson = json_encode($data);

/* Example 4 - escapeUrl */
$myUrl = "https://magento235.loc/pagelayout/show/escapeMethodsTutorial/<br>
<script >location='https://magento235.loc/';</script>";

/* Example 5 - escapeCss */
$css = "background: #000\"><script>alert('hello');</script>";
?>

<!---------------------------------------------------------------------------------------------->

<!-- Example 1 - escapeHtml -->
<?= $block->escapeHtml($block->getTitle()) . '<br>'?>

<!-- Example 2 - escapeJs -->
<?= $block->escapeJs($egypt) . '<br>'?>

<!-- Example 3 - escapeHtmlAttr -->
<div title='<script>console.log("hello");</script>'>

<!-- Example 4 - escapeUrl -->
<a href="<?= $block->escapeUrl($myUrl) ?>">Click on me</a>

<!-- Example 5 - escapeCss -->
<div style="<?= $block->escapeCss($css)?>">

