<?php

namespace Learning\AdminGrid\Model\ResourceModel;

use Learning\AdminGrid\Exception\FieldIsNotValidException;
use Learning\AdminGrid\Validator\GridDataValidator;
use Magento\Framework\Exception\AlreadyExistsException;
use Magento\Framework\Model\AbstractModel;
use Magento\Framework\Model\ResourceModel\Db\AbstractDb;
use Magento\Framework\Model\ResourceModel\Db\Context;

class AdminGrid extends AbstractDb
{
    private $gridDataValidator;

    public function __construct(
        Context $context,
        GridDataValidator $gridDataValidator,
        $connectionName = null
    ) {
        $this->gridDataValidator = $gridDataValidator;
        parent::__construct($context, $connectionName);
    }

    public function _construct()
    {
        $this->_init('testAdminHtml', 'id');
    }

    /**
     * @param AbstractModel $object
     * @return AdminGrid
     * @throws AlreadyExistsException
     * @throws FieldIsNotValidException
     */
    public function save(AbstractModel $object): AdminGrid
    {
        $this->gridDataValidator->validateData($object);

        return parent::save($object); // TODO: Change the autogenerated stub
    }
}
