<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block Title
 */

use Magento\Theme\Block\Html\Title;

?>

<p class="font1">hello my name is test font1</p>
<p class="font2">hello my name is test font2</p>
<p class="font3">hello my name is test font3</p>


<img src='<?php echo $this->getViewFileUrl("images/test5.png"); ?>' alt=”Demo”>
