<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block Title
 */

use Magento\Theme\Block\Html\Title;

?>

<?= '<p>New text Title test</p>' ?>
<?= '<p>New text Title test. New text Title testNew text Title testNew text Title testNew text Title testNew text Title
    testNew text Title testNew text Title testNew text Title testNew text Title testNew text Title testNew text
    Title testNew <br>
    text Title testNew text Title testNew text Title testNew text Title test</p>' ?>

