<?php

namespace Learning\TestTask\Block;

use Magento\Customer\Model\ResourceModel\CustomerRepository;
use Magento\Customer\Model\Session;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\View\Element\Template;

class StatusForm extends Template
{

    /**
     * @var CustomerRepository
     */
    private $customerRepository;
    /**
     * @var Session
     */
    private $customerSession;

    public function __construct(
        Template\Context $context,
        CustomerRepository $customerRepository,
        Session $customerSession,
        array $data = []
    ) {
        $this->customerRepository = $customerRepository;
        $this->customerSession = $customerSession;
        parent::__construct($context, $data);
    }

    /**
     * @throws LocalizedException
     * @throws NoSuchEntityException
     */
    public function getStatus()
    {
        $customerId = $this->customerSession->getCustomerId();
        $customerData = $this->customerRepository->getById($customerId);
        return $customerData->getCustomAttribute(self::CUSTOM_CUSTOMER_ATTRIBUTE_CODE);
    }

}
